# Controller Configuration

keyboard:
  max_linear_mps: 3.5
  max_angular_dps: 120
  acceleration_linear: 0.2
  acceleration_angular: 2.5
  friction_linear: 0.92
  friction_angular: 0.82

ps3:
  max_linear_mps: 3.5
  max_angular_dps: 120
  deadzone: 0.15
  button_mapping:
    emergency_stop: 0 # X button
    circle: 1
    triangle: 2
    square: 3
  axis_mapping:
    left_x: 0
    left_y: 1
    right_x: 2

speed_control:
  initial_factor: 0.07
  min_factor: 0.2
  max_factor: 2.0
  increment: 0.1
